#!/bin/sh
. "/home/ec2-user/kyo/logger.sh"

# スクリプト自身のパスを取得（bashでも.でも動く）
script_path="$(realpath "${BASH_SOURCE[0]:-${0}}")"

log_exec "$script_path" "$@"

#####################################################################
# バッチジョブ
# 業務：ＣＩＦ残高
# 日次：預金計数ワーク作成
#
# 変更履歴
# -------------------------------------------------------------------
# 2024/07/08 新規作成                                    | TSUKINOKI
#####################################################################
# 環境変数の設定
. ${ENV_DIR}/SetEnv_1.sh
# 変数宣言
JOBID=BKTD1106

# ログ退避 (２世代保有)
JOBLOG=${LOG_DIR}/${JOBID}.log
if [ -f ${JOBLOG} ]; then
  cp -pr ${JOBLOG} ${JOBLOG}old
fi

#テーブルを削除して作成
TBL_RE_CREATE()
{
TBL_NAME=$1
TBL_EXT=$2
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト開始 >-----------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/TBLCREATE.sh ${TBL_NAME} ${TBL_EXT} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト終了 >-----------------#\n"
}

#ＳＱＬの実行
SQL_GO()
{
SQL_NAME=$1
printf "\t#--< ${SQL_NAME} の実行開始 >--------------------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/BATCHJOB.sh ${JOBID} ${SQL_NAME} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${SQL_NAME} の実行終了 >--------------------------#\n"
}

date > ${LOG_DIR}/${JOBID}.log

#テーブルの削除/作成
TBL_RE_CREATE T_KT11070D WK01
TBL_RE_CREATE T_KT11070D WK02
TBL_RE_CREATE T_KT11070D WK03
TBL_RE_CREATE T_KT11070D WK04
TBL_RE_CREATE T_KT11070D WK05
TBL_RE_CREATE T_KT11070D WK06
TBL_RE_CREATE T_KT11070D WK10
TBL_RE_CREATE T_KT11070D WK11
TBL_RE_CREATE T_KT11070D WK12
TBL_RE_CREATE T_KT11070D WK13
TBL_RE_CREATE T_KT11070D WK14
TBL_RE_CREATE T_KT11070D WK15
TBL_RE_CREATE T_KT11070D WK16
TBL_RE_CREATE T_KT11070D WK17
TBL_RE_CREATE T_KT11070D WK20
TBL_RE_CREATE T_KT11070D WK18
TBL_RE_CREATE T_KT11070D WK19
TBL_RE_CREATE T_KT11070D WK30
TBL_RE_CREATE T_KT11070D WK21
TBL_RE_CREATE T_KT11070D WK31
TBL_RE_CREATE T_KT11070D WK22

#SQL実行
SQL_GO BKTD1106_01
SQL_GO BKTD1106_02
SQL_GO BKTD1106_03
SQL_GO BKTD1106_04
SQL_GO BKTD1106_05
SQL_GO BKTD1106_06
SQL_GO BKTD1106_10
SQL_GO BKTD1106_11
SQL_GO BKTD1106_12
SQL_GO BKTD1106_13
SQL_GO BKTD1106_14
SQL_GO BKTD1106_15
SQL_GO BKTD1106_16
SQL_GO BKTD1106_17
SQL_GO BKTD1106_20
SQL_GO BKTD1106_18
SQL_GO BKTD1106_19
SQL_GO BKTD1106_30
SQL_GO BKTD1106_21
SQL_GO BKTD1106_31
SQL_GO BKTD1106_22
