#!/bin/sh
. "/home/ec2-user/kyo/logger.sh"

# スクリプト自身のパスを取得（bashでも.でも動く）
script_path="$(realpath "${BASH_SOURCE[0]:-${0}}")"

log_exec "$script_path" "$@"

#####################################################################
# バッチジョブ
# ＣＩＦ動態抽出（SCOPE)
#
#      作成日：2024/10/21
#      作成者：K.Setoguchi
#      更新日：
#      更新者：
#####################################################################
# 環境変数の設定
. ${ENV_DIR}/SetEnv_1.sh
# 変数宣言
JOBID=BKTM1805

# ログ退避 (２世代保有)
JOBLOG=${LOG_DIR}/${JOBID}.log
if [ -f ${JOBLOG} ]; then
  cp -pr ${JOBLOG} ${JOBLOG}old
fi

#テーブルを削除して作成
TBL_RE_CREATE()
{
TBL_NAME=$1
TBL_EXT=$2
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト開始 >-----------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/TBLCREATE.sh ${TBL_NAME} ${TBL_EXT} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト終了 >-----------------#\n"
}

#ＳＱＬの実行
SQL_GO()
{
SQL_NAME=$1
printf "\t#--< ${SQL_NAME} の実行開始 >--------------------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/BATCHJOB.sh ${JOBID} ${SQL_NAME} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${SQL_NAME} の実行終了 >--------------------------#\n"
}

date > ${LOG_DIR}/${JOBID}.log

#ワークテーブルの削除/作成
TBL_RE_CREATE T_KT18050M OBJ
TBL_RE_CREATE T_KT18050M WK1

#SQL実行
SQL_GO BKTM1805_01
SQL_GO BKTM1805_02
SQL_GO BKTM1805_03
SQL_GO BKTM1805_04
SQL_GO BKTM1805_05
SQL_GO BKTM1805_06
SQL_GO BKTM1805_07
SQL_GO BKTM1805_08
SQL_GO BKTM1805_09
SQL_GO BKTM1805_10
SQL_GO BKTM1805_11
SQL_GO BKTM1805_12
SQL_GO BKTM1805_13
SQL_GO BKTM1805_14
SQL_GO BKTM1805_15
SQL_GO BKTM1805_16
SQL_GO BKTM1805_17
SQL_GO BKTM1805_18
SQL_GO BKTM1805_19
SQL_GO BKTM1805_20
SQL_GO BKTM1805_21
