#!/bin/sh
. "/home/ec2-user/kyo/logger.sh"

# スクリプト自身のパスを取得（bashでも.でも動く）
script_path="$(realpath "${BASH_SOURCE[0]:-${0}}")"

log_exec "$script_path" "$@"

#####################################################################
# バッチジョブ
# 日次：統合ＣＩＦ　各契約有無抽出
#                   給振有無、年金有無、公共料金自振数、ローン取引数、機能サービス数
#
#           作成日：2023/02/07
#           作成者：Nagata
#####################################################################
# 環境変数の設定
. ${ENV_DIR}/SetEnv_1.sh
# 変数宣言
JOBID=BNYD0330

# ログ退避 (２世代保有)
JOBLOG=${LOG_DIR}/${JOBID}.log
if [ -f ${JOBLOG} ]; then
  cp -pr ${JOBLOG} ${JOBLOG}old
fi

#テーブルを削除して作成
TBL_RE_CREATE()
{
TBL_NAME=$1
TBL_EXT=$2
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト開始 >-----------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/TBLCREATE.sh ${TBL_NAME} ${TBL_EXT} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト終了 >-----------------#\n"
}

#ＳＱＬの実行
SQL_GO()
{
SQL_NAME=$1
printf "\t#--< ${SQL_NAME} の実行開始 >--------------------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/BATCHJOB.sh ${JOBID} ${SQL_NAME} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${SQL_NAME} の実行終了 >--------------------------#\n"
}

date > ${LOG_DIR}/${JOBID}.log

#テーブルの削除/作成
TBL_RE_CREATE T_NY03000D WK5
TBL_RE_CREATE T_NY03000D WK6
TBL_RE_CREATE T_NY03000D WK7
TBL_RE_CREATE T_NY03000D WK8
TBL_RE_CREATE T_NY03000D WK9

#SQL実行
SQL_GO BNYD0330_01
SQL_GO BNYD0330_02
SQL_GO BNYD0330_03
SQL_GO BNYD0330_04
SQL_GO BNYD0330_05
