#!/bin/sh
. "/home/ec2-user/kyo/logger.sh"

# スクリプト自身のパスを取得（bashでも.でも動く）
script_path="$(realpath "${BASH_SOURCE[0]:-${0}}")"

log_exec "$script_path" "$@"

#####################################################################
# バッチジョブ
# 月次：世帯番号引継ぎ
#
#           作成日：2023/02/28
#           作成者：Shunya.M
#####################################################################
# 環境変数の設定
. ${ENV_DIR}/SetEnv_1.sh
# 変数宣言
JOBID=BNYD0780

# ログ退避 (２世代保有)
JOBLOG=${LOG_DIR}/${JOBID}.log
if [ -f ${JOBLOG} ]; then
  cp -pr ${JOBLOG} ${JOBLOG}old
fi

#テーブルを削除して作成
TBL_RE_CREATE()
{
TBL_NAME=$1
TBL_EXT=$2
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト開始 >-----------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/TBLCREATE.sh ${TBL_NAME} ${TBL_EXT} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト終了 >-----------------#\n"
}

#ＳＱＬの実行
SQL_GO()
{
SQL_NAME=$1
printf "\t#--< ${SQL_NAME} の実行開始 >--------------------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/BATCHJOB.sh ${JOBID} ${SQL_NAME} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${SQL_NAME} の実行終了 >--------------------------#\n"
}

date > ${LOG_DIR}/${JOBID}.log

#テーブルの削除/作成
TBL_RE_CREATE T_NY07000D OBJ
TBL_RE_CREATE T_NY07801D WK1
TBL_RE_CREATE T_NY07802D WK2
TBL_RE_CREATE T_NY07803D WK3
TBL_RE_CREATE T_NY07804D WK4
TBL_RE_CREATE T_NY07804D WK5
TBL_RE_CREATE T_NY07803D WK6
TBL_RE_CREATE T_NY07804D WK7
TBL_RE_CREATE T_NY07804D WK8
TBL_RE_CREATE T_NY07803D WK9
TBL_RE_CREATE T_NY07804D WK10
TBL_RE_CREATE T_NY07803D WK11
TBL_RE_CREATE T_NY07804D WK12

#SQL実行
SQL_GO BNYD0780_01 
SQL_GO BNYD0780_02 
SQL_GO BNYD0780_03 
SQL_GO BNYD0780_04 
SQL_GO BNYD0780_05 
SQL_GO BNYD0780_06 
SQL_GO BNYD0780_07 
SQL_GO BNYD0780_08 
SQL_GO BNYD0780_09 
SQL_GO BNYD0780_10 
SQL_GO BNYD0780_11 
SQL_GO BNYD0780_12 
SQL_GO BNYD0780_13 
