#!/bin/sh
. "/home/ec2-user/kyo/logger.sh"

# スクリプト自身のパスを取得（bashでも.でも動く）
script_path="$(realpath "${BASH_SOURCE[0]:-${0}}")"

log_exec "$script_path" "$@"

#####################################################################
# バッチジョブ
# 月次：世帯番号マージ
#
#           作成日：2023/02/28
#           作成者：Shunya.M
#####################################################################
# 環境変数の設定
. ${ENV_DIR}/SetEnv_1.sh
# 変数宣言
JOBID=BNYD0620

# ログ退避 (２世代保有)
JOBLOG=${LOG_DIR}/${JOBID}.log
if [ -f ${JOBLOG} ]; then
  cp -pr ${JOBLOG} ${JOBLOG}old
fi

#テーブルを削除して作成
TBL_RE_CREATE()
{
TBL_NAME=$1
TBL_EXT=$2
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト開始 >-----------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/TBLCREATE.sh ${TBL_NAME} ${TBL_EXT} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト終了 >-----------------#\n"
}

#ＳＱＬの実行
SQL_GO()
{
SQL_NAME=$1
printf "\t#--< ${SQL_NAME} の実行開始 >--------------------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/BATCHJOB.sh ${JOBID} ${SQL_NAME} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${SQL_NAME} の実行終了 >--------------------------#\n"
}

date > ${LOG_DIR}/${JOBID}.log

#テーブルの削除/作成
TBL_RE_CREATE T_NY06200D OBJ
TBL_RE_CREATE T_NY06201D WK1
TBL_RE_CREATE T_NY06202D WK2
TBL_RE_CREATE T_NY06203D WK3
TBL_RE_CREATE T_NY06201D WK4

#SQL実行
	SQL_GO BNYD0620_01

	## 名寄せキーの個数を KEY_KOSU に 指定すること
	KEY_KOSU=2

	STI_CTR=1                                               ;export STI_CTR
	while [ ${STI_CTR} -lt ${KEY_KOSU} ]
	do
		printf "\t**--< BNYD0620 ループ ${STI_CTR} 回目 >---**\n"
		KEY_NO=`expr LEFT(${STI_CTR}, datalength(${STI_CTR})/4) + 1`
		EXT_ID="OBJ${KEY_NO}"                               ;export EXT_ID
		SQL_GO BNYD0620_02
		CTR=0                                               ;export CTR
		RC=1
		while [ ${RC} != 0 ]
		do
			CTR=`expr LEFT(${CTR}, datalength(${CTR})/4) + 1`
			printf "\t **--< BNYD0620_03 マージ ${CTR} 回目 >--**\n"
			date >> ${LOG_DIR}/${JOBID}.log
			${SHELL} ${SQL_DIR}/BNYD0620_03.sql >> ${LOG_DIR}/${JOBID}.log
			RC=$?
			if [ ${CTR} -ge 10 ]; then
				printf "\t **--< BNYD0620_03 マージ ${CTR} 回目 回数オーバ >--**\n"
				exit 8
			fi
		done
		printf "\t **--< BNYD0620_03 マージ 終了 >--**\n"
		SQL_GO BNYD0620_04
		STI_CTR=`expr LEFT(${STI_CTR}, datalength(${STI_CTR})/4) + 1`                       ;export STI_CTR
	done
	printf "\t **--< BNYD0620 ループ 終了 >-----**\n"
