#!/bin/sh
. "/home/ec2-user/kyo/logger.sh"

# スクリプト自身のパスを取得（bashでも.でも動く）
script_path="$(realpath "${BASH_SOURCE[0]:-${0}}")"

log_exec "$script_path" "$@"

######################################################################
# バッチジョブ
# 日次：管理店変更依頼情報累積処理
#
# 変更履歴
# --------------------------------------------------------------------
# 2016-09-12:新規作成                               | Human KOBAYASHI
######################################################################

# 環境変数の設定 =====================================================
. ${ENV_DIR}/SetEnv_1.sh


# 変数宣言 ===========================================================
JOBID=BSND0208


# ログ退避 (２世代保有) ==============================================
LOG="${JOBID}.log"
LOGSD=2
${SHELL} ${SH_DIR}/LOG_SHIFT.sh ${LOG} ${LOGSD}
JOBLOG="${LOG_DIR}/${LOG}"


# テーブルを削除して作成 =============================================
TBL_RE_CREATE()
{
  DDLID=$1
  PTNID=$2
  printf "\t#--< ${DDLID}_${PTNID} のクリエイト開始 >-----------------#\n" >> ${JOBLOG} 2>&1
  date >> ${JOBLOG} 2>&1
  ${SHELL} ${SH_DIR}/TBLCREATE.sh ${DDLID} ${PTNID} >> ${JOBLOG} 2>&1
  if [ $? != 0 ]; then
    exit 8
  fi
  date >> ${JOBLOG} 2>&1
  printf "\t#--< ${DDLID}_${PTNID} のクリエイト終了 >-----------------#\n" >> ${JOBLOG} 2>&1
}


# テーブルを削除 =====================================================
TBL_DELETE()
{
  DDLID=$1
  PTNID=$2
  printf "\t#--< ${DDLID}_${PTNID} のデリート開始 >-----------------#\n" >> ${JOBLOG} 2>&1
  date >> ${JOBLOG} 2>&1
  ${SHELL} ${SH_DIR}/TBLDEL01.sh ${DDLID} ${PTNID} >> ${JOBLOG} 2>&1
  if [ $? != 0 ]; then
    exit 8
  fi
  date >> ${JOBLOG} 2>&1
  printf "\t#--< ${DDLID}_${PTNID} のデリート終了 >-----------------#\n" >> ${JOBLOG} 2>&1
}


# ＳＱＬの実行  =====================================================
SQL_GO()
{
  SQL_NAME=$1
  TBL_NAME=$2
  printf "\t#--< ${SQL_NAME} の実行開始 >--------------------------#\n" >> ${JOBLOG} 2>&1
  date >> ${JOBLOG} 2>&1
  ${SHELL} ${SQL_DIR}/${SQL_NAME}.sql ${TBL_NAME} >> ${JOBLOG} 2>&1

  if [ $? != 0 ]; then
    exit 8
  fi
  date >> ${JOBLOG} 2>&1
  printf "\t#--< ${SQL_NAME} の実行終了 >--------------------------#\n" >> ${JOBLOG} 2>&1
}

date > ${JOBLOG} 2>&1


# テーブルの削除/作成 ================================================
TBL_RE_CREATE T_SN02080D OBJ


# ＳＱＬ実行 =========================================================
SQL_GO BSND0208_01
SQL_GO BSND0208_02
