#!/bin/sh
. "/home/ec2-user/kyo/logger.sh"

# スクリプト自身のパスを取得（bashでも.でも動く）
script_path="$(realpath "${BASH_SOURCE[0]:-${0}}")"

log_exec "$script_path" "$@"

#####################################################################
# バッチジョブ
# 業務：業務支援系商品
# 日次：顧客商品有無情報作成（当行投信（BESTWAY））
#
# 変更履歴
# -------------------------------------------------------------------
# 2024/01/26 新規作成                             | KODAMA
# 2024/05/10 定時定額(口座開設)追加               | KODAMA
#####################################################################
# 環境変数の設定
. ${ENV_DIR}/SetEnv_1.sh
# 変数宣言
JOBID=BSND2500

# ログ退避 (２世代保有)
JOBLOG=${LOG_DIR}/${JOBID}.log
if [ -f ${JOBLOG} ]; then
  cp -pr ${JOBLOG} ${JOBLOG}old
fi

#テーブルを削除して作成
TBL_RE_CREATE()
{
TBL_NAME=$1
TBL_EXT=$2
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト開始 >-----------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/TBLCREATE.sh ${TBL_NAME} ${TBL_EXT} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${TBL_NAME}_${TBL_EXT} のクリエイト終了 >-----------------#\n"
}

#ＳＱＬの実行
SQL_GO()
{
SQL_NAME=$1
printf "\t#--< ${SQL_NAME} の実行開始 >--------------------------#\n"
date >> ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/BATCHJOB.sh ${JOBID} ${SQL_NAME} >> ${LOG_DIR}/${JOBID}.log
if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${SQL_NAME} の実行終了 >--------------------------#\n"
}

date > ${LOG_DIR}/${JOBID}.log

#テーブルの削除/作成
TBL_RE_CREATE T_SN25000D OBJ


#SQL実行
SQL_GO BSND2500_01
SQL_GO BSND2500_02
SQL_GO BSND2500_03
SQL_GO BSND2500_04
SQL_GO BSND2500_05
SQL_GO BSND2500_06
SQL_GO BSND2500_07
