#!/bin/sh
. "/home/ec2-user/kyo/logger.sh"

# スクリプト自身のパスを取得（bashでも.でも動く）
script_path="$(realpath "${BASH_SOURCE[0]:-${0}}")"

log_exec "$script_path" "$@"

# =========================================================================
# 世代更新(チェンジ) : ＦＧ証券用顧客口座情報 (T_SN00800D)
#                     (入力テーブル残す、BKUPあり)
#
#           作成日付 : 2023-01-30
# =========================================================================

# 環境変数の設定
. ${ENV_DIR}/SetEnv_1.sh

# 変数宣言
JOBID=CSND0800
DDLID=T_SN00800D
PTNID=OBJ
CYL=5
VTBL=

# ログ退避 (２世代保有)
JOBLOG=${LOG_DIR}/${JOBID}.log
if [ -f ${JOBLOG} ]; then
  cp -pr ${JOBLOG} ${JOBLOG}old
fi

# チェンジ処理
date > ${LOG_DIR}/${JOBID}.log
${SHELL} ${SH_DIR}/TBLCHG08.sh ${DDLID} ${PTNID} ${CYL} ${VTBL} >> ${LOG_DIR}/${JOBID}.log

if [ $? != 0 ]; then
  exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
