#!/bin/sh
. "/home/ec2-user/kyo/logger.sh"

# スクリプト自身のパスを取得（bashでも.でも動く）
script_path="$(realpath "${BASH_SOURCE[0]:-${0}}")"

log_exec "$script_path" "$@"

#####################################################################
# バッチジョブ
# 月次：【CC】電話番号優先順情報_集信処理
#
#           作成日：2021/08/24
#           作成者：eBP T.Kodama
# 変更履歴
# -------------------------------------------------------------------
# ===================================================================
#
#####################################################################
# 環境変数の設定
. ${ENV_DIR}/SetEnv_1.sh


JOBID=RKTD0410
FLID=T_KT43000D
HULFT_ID=DCCSF218
export JOBID
export HULFT_ID

# ＨＵＬＦＴ環境変数宣言
PATH=$PATH:/usr/local/HULFT/bin
HULPATH=/usr/local/HULFT/etc
HULEXEP=/usr/local/HULFT/bin
export PATH
export HULPATH
export HULEXEP

# ＨＵＬＦＴ 集信
date > ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${JOBID} HULFT 集信開始 >----------------------#\n" >> ${LOG_DIR}/${JOBID}.log

printf " \n\t     HULFT-ID = DCCSF218 \n" >> ${LOG_DIR}/${JOBID}.log
printf   " \t         File = T_KT43000D \n\n " >> ${LOG_DIR}/${JOBID}.log

#========== HULFT転送 ===================#
. ${HULFT_SH_DIR}/HULFT_RCV.sh   >> ${LOG_DIR}/${JOBID}.log
RC=$?
if [ $RC != 0 ]; then
    date >> ${LOG_DIR}/${JOBID}.log
    printf "\t# ＨＵＬＦＴ集信エラー CD=$RC  #\n" >> ${LOG_DIR}/${JOBID}.log
    exit 8
fi
date >> ${LOG_DIR}/${JOBID}.log
printf "\t#--< ${JOBID} HULFT 集信終了 >----------------------#\n" >> ${LOG_DIR}/${JOBID}.log
